spring.application.name=yelin-api
server.servlet.context-path=/api
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=false
spring.sql.init.mode=never

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:shalukhina;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

server.port=${SERVER_PORT:8080}